[package]
name = "vrac-workspace"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Local workspace lifecycle and synchronization for Vrac clients"

[dependencies]
vrac-engine = { path = "../vrac-engine", version = "0.1.0" }

[dev-dependencies]
tempfile = "3.27.0"
